<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 09.09.2017
 * Time: 9:22
 */

namespace app\components;
use yii\base\Widget;
use app\models\Cats;


class categoriesWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $data = Cats::find()->all();
        return $this->render('categories', compact('data'));
    }
}