<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 09.09.2017
 * Time: 10:00
 */

namespace app\components;
use yii\base\Widget;
use app\models\Posts;


class recentPostWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $query = Posts::find()->select('id, title, description')->orderBy('id DESC');
        $posts = $query->limit('3')->all();
        return $this->render('recentPost', compact('posts'));
    }
}